"""init_schema

Revision ID: 1d5793522c10
Revises: 
Create Date: 2026-06-10 18:43:50.647570
"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '1d5793522c10'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_system', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_activity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fallback_dedupe_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_sport_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('normalized_sport_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('start_time_utc', sa.DateTime(), nullable=True),
    sa.Column('start_time_local', sa.DateTime(), nullable=True),
    sa.Column('local_date', sa.Date(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_distance_m', sa.Float(), nullable=True),
    sa.Column('computed_distance_m', sa.Float(), nullable=True),
    sa.Column('moving_time_s', sa.Float(), nullable=True),
    sa.Column('elapsed_time_s', sa.Float(), nullable=True),
    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
    sa.Column('avg_pace_s_per_km', sa.Float(), nullable=True),
    sa.Column('avg_speed_mps', sa.Float(), nullable=True),
    sa.Column('max_speed_mps', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate_bpm', sa.Float(), nullable=True),
    sa.Column('max_heart_rate_bpm', sa.Float(), nullable=True),
    sa.Column('avg_cadence_spm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fallback_dedupe_key', name='uq_activities_fallback_dedupe_key'),
    sa.UniqueConstraint('source_activity_id', name='uq_activities_source_activity_id')
    )
    op.create_index(op.f('ix_activities_fallback_dedupe_key'), 'activities', ['fallback_dedupe_key'], unique=False)
    op.create_index(op.f('ix_activities_file_hash'), 'activities', ['file_hash'], unique=False)
    op.create_index('ix_activities_local_date', 'activities', ['local_date'], unique=False)
    op.create_index(op.f('ix_activities_source_activity_id'), 'activities', ['source_activity_id'], unique=False)
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('run_activities_seen', sa.Integer(), nullable=False),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('reprocessed_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('skipped_non_run_activities_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_jobs_status'), 'import_jobs', ['status'], unique=False)
    op.create_table('activity_import_diagnostics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('source_activity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parser_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parse_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('points_raw_count', sa.Integer(), nullable=True),
    sa.Column('points_normalized_count', sa.Integer(), nullable=True),
    sa.Column('points_cleaned_count', sa.Integer(), nullable=True),
    sa.Column('fields_detected_json', sa.JSON(), nullable=True),
    sa.Column('fields_dropped_json', sa.JSON(), nullable=True),
    sa.Column('warnings_json', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_import_diagnostics_activity_id'), 'activity_import_diagnostics', ['activity_id'], unique=False)
    op.create_index(op.f('ix_activity_import_diagnostics_import_job_id'), 'activity_import_diagnostics', ['import_job_id'], unique=False)
    op.create_index(op.f('ix_activity_import_diagnostics_source_activity_id'), 'activity_import_diagnostics', ['source_activity_id'], unique=False)
    op.create_table('activity_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('simplified_points_json', sa.JSON(), nullable=True),
    sa.Column('original_point_count', sa.Integer(), nullable=False),
    sa.Column('simplified_point_count', sa.Integer(), nullable=False),
    sa.Column('simplification_tolerance_m', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_routes_activity_id'), 'activity_routes', ['activity_id'], unique=True)
    op.create_table('activity_splits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('split_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('split_index', sa.Integer(), nullable=False),
    sa.Column('start_distance_m', sa.Float(), nullable=False),
    sa.Column('end_distance_m', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('avg_pace_s_per_km', sa.Float(), nullable=True),
    sa.Column('avg_heart_rate_bpm', sa.Float(), nullable=True),
    sa.Column('avg_cadence_spm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_splits_activity', 'activity_splits', ['activity_id', 'split_type', 'split_index'], unique=False)
    op.create_index(op.f('ix_activity_splits_activity_id'), 'activity_splits', ['activity_id'], unique=False)
    op.create_table('best_efforts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('duration_s', sa.Float(), nullable=False),
    sa.Column('pace_s_per_km', sa.Float(), nullable=False),
    sa.Column('start_elapsed_time_s', sa.Float(), nullable=True),
    sa.Column('end_elapsed_time_s', sa.Float(), nullable=True),
    sa.Column('start_distance_m', sa.Float(), nullable=True),
    sa.Column('end_distance_m', sa.Float(), nullable=True),
    sa.Column('start_lat', sa.Float(), nullable=True),
    sa.Column('start_lon', sa.Float(), nullable=True),
    sa.Column('end_lat', sa.Float(), nullable=True),
    sa.Column('end_lon', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_best_efforts_activity_id'), 'best_efforts', ['activity_id'], unique=False)
    op.create_index('ix_best_efforts_distance_duration', 'best_efforts', ['distance_m', 'duration_s'], unique=False)
    op.create_table('track_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.Column('point_index', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('elapsed_time_s', sa.Float(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('heart_rate_bpm', sa.Float(), nullable=True),
    sa.Column('cadence_spm', sa.Float(), nullable=True),
    sa.Column('speed_mps', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_points_activity_id'), 'track_points', ['activity_id'], unique=False)
    op.create_index('ix_track_points_activity_index', 'track_points', ['activity_id', 'point_index'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_track_points_activity_index', table_name='track_points')
    op.drop_index(op.f('ix_track_points_activity_id'), table_name='track_points')
    op.drop_table('track_points')
    op.drop_index('ix_best_efforts_distance_duration', table_name='best_efforts')
    op.drop_index(op.f('ix_best_efforts_activity_id'), table_name='best_efforts')
    op.drop_table('best_efforts')
    op.drop_index(op.f('ix_activity_splits_activity_id'), table_name='activity_splits')
    op.drop_index('ix_activity_splits_activity', table_name='activity_splits')
    op.drop_table('activity_splits')
    op.drop_index(op.f('ix_activity_routes_activity_id'), table_name='activity_routes')
    op.drop_table('activity_routes')
    op.drop_index(op.f('ix_activity_import_diagnostics_source_activity_id'), table_name='activity_import_diagnostics')
    op.drop_index(op.f('ix_activity_import_diagnostics_import_job_id'), table_name='activity_import_diagnostics')
    op.drop_index(op.f('ix_activity_import_diagnostics_activity_id'), table_name='activity_import_diagnostics')
    op.drop_table('activity_import_diagnostics')
    op.drop_index(op.f('ix_import_jobs_status'), table_name='import_jobs')
    op.drop_table('import_jobs')
    op.drop_index(op.f('ix_activities_source_activity_id'), table_name='activities')
    op.drop_index('ix_activities_local_date', table_name='activities')
    op.drop_index(op.f('ix_activities_file_hash'), table_name='activities')
    op.drop_index(op.f('ix_activities_fallback_dedupe_key'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
